version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: created_at_timestamp
        tests:
          - not_null

  - name: stg_subscription_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: event_timestamp
        tests:
          - not_null
